version: "3.8"

services:
  mongodb:
    image : mongo
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - /Users/john.gilliland/docker/volumes/mongodb/database:/data/db 

    restart: unless-stopped
